"""ML Learning Lab for Analysts."""

from .config import APP_ID, APP_VERSION, CONTENT_VERSION, CURRICULUM_SCHEMA_VERSION, SCHEMA_VERSION

__all__ = [
    "APP_ID",
    "APP_VERSION",
    "CONTENT_VERSION",
    "CURRICULUM_SCHEMA_VERSION",
    "SCHEMA_VERSION",
]
